### ISSUE TITLE
Improve manual 2 section on editing patches (intelligent patching) and more

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#186]
This is a reboot of https://github.com/pure-data/pddp/issues/92 

Doing the below list stuff here https://github.com/pure-data/pure-data/compare/master...porres:pure-data:manual-chapter2-revsion

# Document "intelligent patching"
source: * https://vimeo.com/273707442 * https://vimeo.com/279631360 * https://vimeo.com/340437816
- [x] Document 'tab' navigation (objects, connections, outlets and inlets!)
- [x] Document autopatching
- [x] duplicate connections with cmd+d
- [x] shift
     - [x] swap connections: for a selected a connection, click and shift on another connection to swap them.
     - [x] If objects are unselected, click instead of releasing to keep making connections. 
     - [x] connect one to many
     - [x] connect many to one
     - [x] for 2 selected objects, it connects all inlets/outlets
     - [x] connect the same outlet of selected objects into many inlets of a single object that is also selected
- [x] cmd+k 
     - [x] select 2 objects connect them.
     - [x] Repeat to connect more outlets to inlets
     - [x] For signal objects, repeated to fan out an outlet to more inlets
     - [x] select object and connection or 3 objects to insert
     - [x] select 3 objects to bypass (this and above can be non leftmost connection).
- [x] documenting 'paste + replace'
- [x] Document triggerize
     - [x] insert a trigger when an output is connected to may inlets of one or more objects
     - [x] insert a dummy object and type on it to replace for another. Select connection and do 'comd+t'
     - [x] insert a dummy audio object (nop~) in a signal connection (mention it doesn't have to be leftmost here and above)
- [x] Include screenshots of "Intelligent patching
---------------------------------------------
# General Stuff

- [x] Document more details from the main Pd window, mention turning DSP on and off and 'clear console'
- [x] expand 2.1.4. patches and files to show how to create, set font size and close a patch with shortcuts from th 'file' menu
- [x] Document 'esc' to cancel selection 
- [x] improve copy/paste/duplicate/cut section
- [x] Document moving objrets with arrows
- [x] Document 'tyding up'
- [x] Include Of mentioned Menus (*File*, *Edit*, *Put* and *Media*)
- [x] resolve differences in macOS resp. Linux/Win on **2.1.1.**

**Comment by porres** [comment]
maybe a new 2.3 entry on 'intelligent patching' makes sense? We can then divide into categories (autopatching, shift, control+k) and we keep 2.6 for the most basic stuff

Control-q "quits" Pd, but asks you to confirm the quit. To quit without having to confirm, use command-shift-Q. --> Not true in Macs

Put this somewhere else, maybe after  2.1.1, with a Pd Menu screenshot.

add File Menu screenshot in 2.1.4. patches and files

**Comment by ben-wes** [comment]
@porres : let me know how or if i can contribute here from here still - since i'm a bit lost now after the discussions and not sure if i should continue editing the initial document?

**Comment by Lucarda** [comment]
porres-data™ has started his usual ...

@porres how about coping all folder `1.manual` into somewhere on branch https://github.com/pure-data/pddp/tree/wip-0.55

so we have access to only the manual. You (with us helping) go through all the changes and include the new pics.

When it's done you copy all the contents of the folder into your `documentation` branch: yes a big overwrite, all the changes are there so you: 

`git add -A` (add all the new pics)
`git commit -am "you name it"`

we can help you better this way, I think. 

Then we delete `wip-0.55` branch

What do you say?

**Comment by porres** [comment]
how harder is it to collaborate to a branch in my repo?

I started a new branch by the way and made a big revision up to 2.3 https://github.com/pure-data/pure-data/compare/master...porres:pure-data:manual-chapter2-revsion

next, rename 2.3 to "inteligent" pathcing and move things up (2.3 becomes 2.4, etc...)

**Comment by Lucarda** [comment]
I would like to use `<code>` for referring to a key or key combination.

`<code>ctrl/cmd + /</code>`

instead of `<bold>`

`<b>ctrl/cmd + /</b>`

not only I liked better but it will be of much use if we ever convert the .htm to .md (we might need to do this in the future)

also I don't like much `ctrl/cmd` we better use one or the other.


I can handle working on your repo. Do I go ahead with my changes?

**Comment by porres** [comment]
>  Do I go ahead with my changes?

yes

**Comment by Lucarda** [comment]
done via https://github.com/porres/pure-data/pull/35

**Comment by porres** [comment]
> also I don't like much ctrl/cmd we better use one or the other.

even though I am an apple guy, feels 'ctrl' should be preffered... mac people know that 'control' is 'command'

**Comment by porres** [comment]
new idea, I think 2.1.4. patches and files should expand and show how to create, set font size and close a patch whith shortcuts from th 'file' menu

**Comment by porres** [comment]
> even though I am an apple guy, feels 'ctrl' should be preffered... mac people know that 'control' is 'command'

nonetheless we also have 'control' key in mac... now I feel that having both makes sense

**Comment by porres** [comment]
for now I'm leaving 'cmd'...

**Comment by porres** [comment]
ok @Lucarda , made more revisions, can you take care of adding pictures/screenshots of menus?

"Post screenshots of Menus. the File, Edit, Put and Media Menus are mentioned in chapter 2, so let's add them where they are mentioned. Edit Menu's screenshot could be right at the beggining of 2.2. editing Pd patches and 'Put Menu' at creating boxes subsection."

**Comment by porres** [comment]
I'm now gonna add a new section and start documenting check boxes under the 'Document intelligent patching'

**Comment by porres** [comment]
added 2.3 on 'advanced editing' to document checkboxes under 'intelligent patching'

**Comment by porres** [comment]
Ok, just documented tab navigation, autopatch, duplicate connections and 'shift'…

only 'cmd + k', triggerize and paste replace to go... will work some more today, but this is something I could do and finish in a day, so no need to wait post .55 :) what I want help with is images... I left (INCLUDE PIC) remarks...

**Comment by porres** [comment]
> Ok, just documented tab navigation, autopatch, duplicate connections and 'shift'…

https://github.com/porres/pure-data/commit/8774e0f3fd658a96e06e4a60d41bf0435b7415c1

**Comment by Lucarda** [comment]
I'm leaving home for the weekend but i'm carring a machine. Will try to get the pics (i have a linux usb drive with debian10 lxqt that i used for the actual pics).

**Comment by porres** [comment]
great, cmd+k is done, only  triggerize and paste replace to go...

If I have nothing to do, I'll finish this over the weekend :)

**Comment by porres** [comment]
here's a picture model for swaping connections

![Screen Shot 2024-03-15 at 18 01 22](https://github.com/pure-data/pddp/assets/5360142/c0951070-598e-4add-b1e6-c2de1e5cef48)

**Comment by porres** [comment]
ok, only triggerize left to go... I'm calling it a day... but it's all almost done...

here's a patch I used to guide me and the above screenshot is from it... no paste replace and triggerize here yet 

[chapter2.pd.zip](https://github.com/pure-data/pddp/files/14621031/chapter2.pd.zip)

**Comment by porres** [comment]
ok, there's a thing IOhanness does at the end of the last video, and it's not possible on a mac... 
* `tab` cycling through target inlets while dragging (only possible on Linux and Windows since it relies on manipulating the mouse position)

I can't test it, so how does it work? 

@Lucarda , @ben-wes ?

**Comment by Lucarda** [comment]
> (only possible on Linux and Windows since it relies on manipulating the mouse position) 

strange. don't understand what's the mac restriction on "manipulating the mouse position"

it works for me as in the video on Windows.

PS: My debian10 ltqx is very old and i got in troubles. Tomorrow i'll try to get a modern version and compile Pd to get the pics.

**Comment by porres** [comment]
> it works for me as in the video on Windows.

I dont understand how it works, can you explain it? It is the last thing for me to document now.... just included triggerize

I also don't know what is the restriction in mac

**Comment by porres** [comment]
there is a shortcut in Pd that requires us to use the 'control' key in mac (not the 'commnd' one). What is the corresponding key on PCs?

**Comment by porres** [comment]
where is 'edit preferences' on PCs?

**Comment by Lucarda** [comment]
> I dont understand how it works, can you explain it?


```
[unpack 0 0 0]

[pack 0 0 0]
```

make a connection from outlet 1 to inlet 1 but don't release the click when you are over inlet 1. While holding the mouse button pressed on 1st inlet. press the `tab` key. it will connect 1st outlet to 2nd inlet. pres `tab` ... . connection is done when you release the mouse button.

**Comment by Lucarda** [comment]
> where is 'edit preferences' on PCs?

![pdprefs](https://github.com/pure-data/pddp/assets/25239522/38cc3f34-e103-4e90-9bf8-acf9eb62c462)

**Comment by Lucarda** [comment]
> there is a shortcut in Pd that requires us to use the 'control' key in mac (not the 'commnd' one). 

which shortcut?


> What is the corresponding key on PCs?

don't know.

**Comment by porres** [comment]
> make a connection from outlet 1 to inlet 1 but don't release the click when you are over inlet 1. While holding the mouse button pressed on 1st inlet. press the tab key. it will connect 1st outlet to 2nd inlet. pres tab ... . connection is done when you release the mouse button.

funny this can't be done on macs, how you can't  "manipulate the mouse position"

> which shortcut?

show previous/next tab

![Screen Shot 2024-03-16 at 10 48 00](https://github.com/pure-data/pddp/assets/5360142/fc2ee661-0cee-47c8-a9df-0a8d42ecdc47)

**Comment by porres** [comment]
funny that in mac you dont have those things under "File". I wonder why...

**Comment by porres** [comment]
Anyway, I'm done, just add some pics and we're good to go, you both can proof read my changes, look for typos, see if the text makes sense and if I missed anything from "intelligent patching". I will do, of course, more revisions

**Comment by porres** [comment]
let's modernize some of the pictures... fig11.1 needs a new screenshot, as it has a whole new look and design

cyclone search in deken shows 0.3, it is in 0.8.1 now, also, deken looks different with the new version, let's show it

**Comment by porres** [comment]
fig4.1 should also be updated

**Comment by porres** [comment]
also, I don't like fig1.1 and how it shows that priority error, that shouldn't be there, right?

**Comment by Lucarda** [comment]
@porres there's https://github.com/porres/pure-data/pull/36 with many updates

this PR covers

- updating the index with the new sections.
- updating internal links.
- breaking long lines in the code.
- update many of existing images.

does not covers

- new images.

**Comment by Lucarda** [comment]
also: @porres i liked very much how you integrated all the data into the manual. I'm having trouble with generating the new images, may be you already have a proper visualization already in mind?.

can you (or @ben-wes) do the new pics?

if there's trouble integrating them you can send me those as patches so i screen them?

whatever it comes up i think the naming scheme could be changed so as to avoid having `fig.x.x.png`. (but may be i'm wrong).

**Comment by ben-wes** [comment]
> can you (or @ben-wes) do the new pics?

i could check the current state of this and create some snapshots later today (CET). @porres let me know if this sounds good to you or if you plan to do that yourself.

**Comment by porres** [comment]
sounds great

**Comment by ben-wes** [comment]
> if there's trouble integrating them you can send me those as patches so i screen them?

i'd do both: create pictures and add a zip of corresponding patches here (if anyone cares about consistent appearance - since my macos screenshots will look different from win/linux ... although i'd at least check that the resolution matches)

> whatever it comes up i think the naming scheme could be changed so as to avoid having `fig.x.x.png`. (but may be i'm wrong).

what scheme do you have in mind? when seeing the current state, it's a bit confusing to me, too, since with the increasing ids, adding pictures anywhere inbetween doesn't work well.

how about renaming them to `fig<chapter>.<slug>.png` where the slug would actually describe them (in most cases derived from the corresponding headline)? i could do that for all pictures.

and i'd also replace all jpgs with pngs since the latter don't really make sense for these kinds of screenshots.

**Comment by Lucarda** [comment]
if you are not going to do all the html stuff simply supply the **new** pics with the new names scheme.

> how about renaming them to `fig<chapter>.<slug>.png` where the slug would actually describe them (in most cases derived from the corresponding headline)? 

- ok, use `fig<chapter>.<slug>.png` for the *new* files only. (it could be `fig-ch2-<the-slug>.png`) 
  - (no "white space" in file name (you-know-what-i-mean))

> i could do that for all pictures.
- ok

  
> and i'd also replace all jpgs with pngs since the former don't really make sense for these kinds of screenshots.

- ok (if possible just convert the existing file (i think).

**Comment by ben-wes** [comment]
> ok, use [...] for the new files only.

ok, i'd proceed with `fig-ch<chapter-number>-<the-slug>.png` ... so no more period in the name except for the file extension?

> no "white space" in filename (you-know-what-i-mean)

yep! that's what i was mainly thinking of when referring to "slugs". :)

> if possible just convert the existing files

i wouldn't suggest that - since then the lossless png compression will persist the jpg artifacts (which will create bigger pngs without any advantage). let's see ... i'd do that last anyway - but if so, we should create new images for the current jpgs, i think.

**Comment by Lucarda** [comment]
i wouldn't suggest that - since then the lossless png compression will persist the jpg artifacts (which will create bigger pngs without any advantage). let's see ... i'd do that last anyway - but if so, we should create new images for the current jpgs, i think.

ok. go ahead with new ones. (thanks for pointing it out, i know nothing of pics and the `jpg`s were in the original manual, so i just use the same file extension)

**Comment by ben-wes** [comment]
> ok. go ahead with new ones.

alright, thanks for the clarifications! i'll start with this in ~5h then!

one more minor question came up when browsing through the current version: for me, there was one case where the shortcut text had a line break. can we use `&nbsp;` for the spaces in shortcuts or will that further complicate the conversion back to md?

**Comment by ben-wes** [comment]
(ah, i think `&nbsp;` anyway&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<-- like here)

**Comment by Lucarda** [comment]
i could not find the line break but anyhow yes replace it (it shouldn't be there). :)

**Comment by ben-wes** [comment]
sorry - that a misunderstanding since my words weren't very precise: there's no actual newline character or so. the line is just breaking like it should :) - but i would prevent the shortcuts to break with the `&nbsp;`s

![image](https://github.com/pure-data/pddp/assets/1923787/7c02dcbf-128d-47a3-9052-0aae4619bdc2)

**Comment by Lucarda** [comment]
that could be

```
<P> <code>Cmd  + Q</code> "quits" Pd, but asks you to confirm the quit.</br>  
To quit without having to confirm, use <code>Cmd + shift + Q</code>.
```

**Comment by ben-wes** [comment]
> that could be

ok, sure - that's a good option to avoid it in this case! anyway, i'd just use `<code>Cmd&nbsp;+&nbsp;+anykey</code>` for shortcuts, ok?

and then please choose the object size / resolution for the screenshot ... :)
(i assume we use the default of 12pt regular?)

![Screenshot 2024-03-18 at 13 04 51](https://github.com/pure-data/pddp/assets/1923787/2adcf281-ddef-4b2a-ba6f-cd38fc544b52)
![Screenshot 2024-03-18 at 13 05 06](https://github.com/pure-data/pddp/assets/1923787/3c0a37f4-5164-4324-bde3-cea152007a7e)
![Screenshot 2024-03-18 at 13 05 23](https://github.com/pure-data/pddp/assets/1923787/3d40dbe8-8e53-464c-b1d4-ab2706afb988)
<img alt="Screenshot 2024-03-18 at 13 05 41" src="https://github.com/pure-data/pddp/assets/1923787/71a3fb0c-a772-47da-8eae-663e73b57ac2">
<img alt="Screenshot 2024-03-18 at 13 06 29" src="https://github.com/pure-data/pddp/assets/1923787/97be7c56-6509-4320-a369-5c9d07984f8c">
<img alt="Screenshot 2024-03-18 at 13 06 49" src="https://github.com/pure-data/pddp/assets/1923787/e47d2045-83f5-429e-96cd-d79d5ce68810">

**Comment by Lucarda** [comment]
> `<code>Cmd&nbsp;+&nbsp;anykey</code>` 

i think its useless inside a `<code>` tag as it indicates no prossessing just text (had not checked it out)

> 12pt regular?

12 or 16 its ok.

**Comment by ben-wes** [comment]
> i think its useless inside a `<code>` tag as it indicates no prossessing just text (had not checked it out)

since `<code>` in html is just another formatting tag, it actually works:

![Screenshot 2024-03-18 at 13 20 33](https://github.com/pure-data/pddp/assets/1923787/809b7d44-774e-4431-826e-f6e6ed6d7a79)
... in markdown, it would be different of course since it gets interpreted as "keep everything here as is".
 
> 12 or 16 its ok.

ok, will use 16 then if @porres doesn't object.

**Comment by ben-wes** [comment]
current version here: https://github.com/porres/pure-data/pull/37

did not upload the pictures yet. but should hopefully get that done today still as well. will follow up here ... if there are any comments already, let me know!

**Comment by ben-wes** [comment]
and damn ... that's quite some work that went into this already from your side. hats up!

**Comment by Lucarda** [comment]
@ben-wes if this helps you can just supply the new pics. the rest is good enough and we don;t need to change it.

**Comment by ben-wes** [comment]
> @ben-wes if this helps you can just supply the new pics. the rest is good enough and we don;t need to change it.

thanks! ... i definitely won't make manage to recreate all images today. but anyway - could still do this in the coming days. still a bit left til 0.55! :)

**Comment by Lucarda** [comment]
> but anyway - could still do this in the coming days. still a bit left til 0.55! :)

we don't know that. we just need the new pics. if they are not there for this release they'll go to the next.

**Comment by ben-wes** [comment]
feel free to give feedback to the first bunch:
https://github.com/porres/pure-data/pull/37/commits/0d2e01936eacb0c3fec8a6d337ae3db2d61cfabb

**Comment by ben-wes** [comment]
(one thing that i'll improve with a bit more time is to include the cursor in some cases)

**Comment by Lucarda** [comment]
> feel free to give feedback to the first bunch:

very nice.

**Comment by ben-wes** [comment]
done for now! i hope, the changes in text are not too radical! ... i tried to read them from a non-native-speaker-pd-beginner's perspective.

the patches are not exactly very original. one could spend a lot of time with that and also use this opportunity to actually present some nice little patches there. we could still do that at some point. for now i hope that they illustrate their topic. and here are all the patches in the last state (maybe i messed some up - not sure):

* [docs-patches.zip](https://github.com/pure-data/pddp/files/14643682/docs-patches.zip)

cheers and goodnight for today. :)

**Comment by ben-wes** [comment]
(ah ... and as i meant before: i can still update other pictures accordingly, of course. just not today. and also the animated gifs might be worth a try ...)

**Comment by Lucarda** [comment]
@ben-wes thanks!!!

> also the animated gifs might be worth a try 

they are nice but they will be all there consuming cpu while the ch2 is in the browser and we want to avoid that.

i'll start to include your pics in the html in 1hour.

**Comment by ben-wes** [comment]
> they [animated gifs] are nice but they will be all there consuming cpu while the ch2 is in the browser and we want to avoid that.

alright. that's a good point - then let's skip that. the illustrations show steps that hopefully suffice or could also be improved.

> i'll start to include your pics in the html in 1hour.

oh ... did i get anything wrong now? i have them included in the html. hope, that wasn't wrong. also text is edited in the html. but i didn't miss some md -> html workflow now hopefully?

**Comment by ben-wes** [comment]
anyway ... should be all transparent in the PR, i hope. but let me know if i did stuff that i wasn't supposed to do!

**Comment by Lucarda** [comment]
oh! i missed https://github.com/porres/pure-data/pull/37

cool. i'll grab it

**Comment by Lucarda** [comment]
> but let me know if i did stuff that i wasn't supposed to do!

totally fantastic!!!.
I think we are done. May be @porres will go for further revisions or start to work on another chapter.

:)

**Comment by ben-wes** [comment]
thanks! i just checked a bit more ... there are some flaws still and i'll probably find more tomorrow:
* fig-ch2-dis-connect-insert-box-to-connection is not correct (should include the box on the right)
* found some text in the beginning where pd window is mentioned twice (also for patch window), which is confusing

... but anyway - hopefully not too much left to do! :)

**Comment by Lucarda** [comment]
right.

there are also some `(INCLUDE PIC).` in the html to delete.

**Comment by Lucarda** [comment]
from the comment above https://github.com/pure-data/pddp/issues/186#issuecomment-2000130567

@porres i need to add 2 more screens. unbelievably with debian lxqt it seems impossible. is like when i leave the screen with an unfolded Pd menu, the key to get the screenshot does not respond anymore. :(

**Comment by Lucarda** [comment]
we have at **"2.1.1. The main window, canvases, and printout"** a perfect description but only for macOS. here most of what is described does not correspond to Linux/Windows(which are equals) windows/menus.

**Comment by Lucarda** [comment]
@porres i'm done via https://github.com/porres/pure-data/pull/38

it includes

- add screens for File, Edit, Put and Media menus
- small clarification on different menus on macOS respc. Linux/Windows

**Comment by ben-wes** [comment]
i updated my branch to fix the (INCLUDE ...) comments and update the picture. i based this on lucardas changes - therefore didn't create a PR yet (although they wouldn't collide i assume).
https://github.com/ben-wes/pure-data/tree/manual-ch2-revision

**Comment by Lucarda** [comment]
@ben-wes can you undo 

https://github.com/ben-wes/pure-data/blob/bcd8a0fd2cabfc3cc354b0e0c15fdd093366a027/doc/1.manual/pdmanual.css#L88

on your next PR

and solve what you tried to fix via a `</br>`. this puts us on trouble rendering code in `x6.htm#s6.4` "pd commandline"

**Comment by ben-wes** [comment]
> @ben-wes can you undo
> https://github.com/ben-wes/pure-data/blob/bcd8a0fd2cabfc3cc354b0e0c15fdd093366a027/doc/1.manual/pdmanual.css#L88

reverted that commit now. it's also not really critical to avoid these line breaks.
i just changed that here since it was so simple and thought i had checked the other docs (thinking, they used `<pre>` anyway where this might conflict. damn).

**Comment by ben-wes** [comment]
and made a PR now: https://github.com/porres/pure-data/pull/39

... hope, i did this right and it's the correct procedure now to have this based on https://github.com/porres/pure-data/pull/38

**Comment by ben-wes** [comment]
for readability, it might be nice to change the appearance a bit at some points. but in this case, the `<kbd>` tag would probably be good, which we don't need to support yet now (but at least, it wouldn't conflict with other `<code>` usage.

here, it currently looks like this:
![Screenshot 2024-03-19 at 11 43 15](https://github.com/pure-data/pddp/assets/1923787/4f969f0e-de36-42da-b961-9020a522830c)

this would be more clear to me with a bit more padding, bold font and not much bigger than the rest of the paragraph:
![Screenshot 2024-03-19 at 11 46 45](https://github.com/pure-data/pddp/assets/1923787/a7e55d8b-283c-477d-b90c-603456a95c4c)

... or even in a more typical way (as @porres originally intended, i think):
![Screenshot 2024-03-19 at 11 49 19](https://github.com/pure-data/pddp/assets/1923787/1a66a6f1-794b-4123-9648-584786855a49)

... but all of this is definitely "nice-to-have" and not urgent. :)

**Comment by Lucarda** [comment]
i would say do as you like. if we ever convert to `.md` we are going to do it just once and it already needs many things that had to be done manually. in the case of `<key>` we can remember this conversation and replace all occurrences for `kbd` and replace them with `code` just before conversion and we are done.

it looks nicer with `<kbd>`. so if you want it go for it.

**Comment by ben-wes** [comment]
> it looks nicer with `<kbd>`. so if you want it go for it.

alright, thanks! @porres : let me know if you have any preferences or thoughts on this and i'll include the changes then.

btw. how should we deal with https://github.com/pure-data/pddp/tree/wip-0.55/keyboard-interaction now? it's a bit dead, right? :)

**Comment by ben-wes** [comment]
added the change to https://github.com/porres/pure-data/pull/39

... this can be easily reverted, of course. but maybe good to check on some other browsers as well anyway.

**Comment by Lucarda** [comment]
renders nicely here on Windows Chrome (click to enlarge)

![kbd](https://github.com/pure-data/pddp/assets/25239522/b3a3062c-8f92-4d1f-91c8-6ecc74826283)

**Comment by ben-wes** [comment]
Here are the updated patches once more:
* [docs-patches.zip](https://github.com/pure-data/pddp/files/14651922/docs-patches.zip)

**Comment by ben-wes** [comment]
this would be another shortcut-formatting option - but i think, we'll stick with the subtle version?

![image](https://github.com/pure-data/pddp/assets/1923787/2f938fe1-8787-4d10-9653-d8988ebe650b)

**Comment by porres** [comment]
guys, been busy, but happy with the great work you've been doing. Really happy and proud of the team work here! I think we're basically done and we have a month or so to still polish and include this in the next release, yay!

**Comment by ben-wes** [comment]
btw, i just realized that the manual already includes an animated gif in `x4.htm#s2.2` (not sure if that was mentioned before).

i think that the static pictures work alright for now anyway - but still: if you feel like there are 1 or 2 cases where this might help, i'd give it a try!

**Comment by Lucarda** [comment]
> (not sure if that was mentioned before)

yes it was here:

https://github.com/pure-data/pddp/issues/92#issuecomment-1996000430

**Comment by ben-wes** [comment]
> yes it was here

ah, damn, sure! sorry for the noise - i herewith redraw my last comment again.

**Comment by Lucarda** [comment]
@ben-wes If you can, can you do a pic that we can use to replace the animated `.gif` for deken?

**Comment by Lucarda** [comment]
Sidenote: You can check for yourself how much cpu it takes to render the animated `.gif`. for me if i open chrome's taskmanager it rises to 45% when the `.gif` is on display. then (when is not visible) cpu goes back to 1% or so.

**Comment by ben-wes** [comment]
> Sidenote: You can check for yourself how much cpu it takes to render the animated `.gif`. for me if i open chrome's taskmanager it rises to 45% when the `.gif` is on display. then (when is not visible) cpu goes back to 1% or so.

crazy. can confirm. a lot less here for me - but still way too much for a little animated gif. just noting: i won't manage to create this pic today, so don't be surprised if there's no activity from my side here!

**Comment by Lucarda** [comment]
> so don't be surprised if there's no activity from my side here!

no trouble at all. feel free to not do it. but if (when) you can we are better. 

:)

**Comment by porres** [comment]
we could photoshop to include a the hand to mimick how it actually looks when clicking and draggin

**Comment by porres** [comment]
I think it'd be nice if we had a caption for all pictures in the manual

**Comment by porres** [comment]
- fig7.3.jpg annoys me, right number box could be better aligned with a straight connection

**Comment by porres** [comment]
we have an inconsistency with standardizatoin. I capitalized the first letter of all sections in chapter 2, as it was the case of chapter 4. I like it better when capitalized. But links to it and other chapters still star with lower case

**Comment by porres** [comment]
anyway, made some edits and made these remarks, still quite busy, cheers

**Comment by porres** [comment]
hey, in 2.6.1. Audio and messages, can we include a pic to show how to set DSP on and off in a patch?

![Screen Shot 2024-03-20 at 16 52 38](https://github.com/pure-data/pddp/assets/5360142/8063d543-7a81-4f72-8e5a-10fa9c8d824c)

**Comment by ben-wes** [comment]
> we could photoshop to include a the hand to mimick how it actually looks when clicking and draggin

will do

**Comment by ben-wes** [comment]
> * fig7.3.jpg annoys me, right number box could be better aligned with a straight connection

if fine for you, @Lucarda, I'd redo all jpgs as png anyway

**Comment by Lucarda** [comment]
> if fine for you, @Lucarda, I'd redo all jpgs as png anyway

go ahead.

**Comment by Lucarda** [comment]
> we have an inconsistency with standardizatoin. I capitalized the first letter of all sections in chapter 2, as it was the case of chapter 4. I like it better when capitalized. But links to it and other chapters still star with lower case

done via https://github.com/porres/pure-data/pull/42

- all sections and their links start with upper case.

**Comment by Lucarda** [comment]
just some correction from my side about the animated `.gif`.

**45%** is the reading of cpu usage i get from chrome's taskmanager but using Windows' taskmanager i get **12%**. now on the same hardware but using firefox on Linux gives me **6%**.

anyway i want to avoid as much as possible animated `.gif`s.

**Comment by ben-wes** [comment]
i created PR https://github.com/porres/pure-data/pull/43 now, which includes cursors and a suggestion for the deken image (i can make more variations there, of course!)

next up for me would be:
* dsp on/off image
* replace jpgs with pngs

**Comment by porres** [comment]
Looking forward to the 'dsp on/off image'.... thenI guess we're kinda done?

**Comment by porres** [comment]
Oh, 1st picture in 2.8.1 still not realigned, huh? can you do that too @ben-wes ?

**Comment by ben-wes** [comment]
https://github.com/porres/pure-data/pull/44 should now include all missing changes. but i did not proof-read yet again.

**Comment by ben-wes** [comment]
> we still need to adapt the lines here to all the changed added/renamed/removed images: https://github.com/porres/pure-data/blob/65fba0333d2e44efa828a182fb34ee1774588098/doc/Makefile.am#L57

... should be done with my last commit in the PR. but i didn't test yet with an actual build!

**Comment by porres** [comment]
we can add a picture in 2.2.6. Connecting and disconnecting boxes

**Comment by Lucarda** [comment]
@ben-wes there was a missing `./1.manual/fig-ch4-deken-install.png \` in the `makefile.am`

the best way to update this is by manually running:

```
find . -type f -not -path "./Makefile*" | sort | awk '{print "    ", $1, "\\"}'; echo '     $(empty)'
```

source: https://github.com/pure-data/pure-data/blob/54f42a918bc4c01d33aabfcd078a6105418143f7/doc/Makefile.am#L54


standing at the `doc` folder. then you can copy from the terminal and paste on `makefile.am`

you might do it after you add the "Connecting and disconnecting boxes" pic

:)

**Comment by ben-wes** [comment]
> @ben-wes there was a missing `./1.manual/fig-ch4-deken-install.png \` in the `makefile.am`
> 
> the best way to update this is by manually running:

oh damn ... i should possibly start reading comments at some point. thanks for the correction and mentioning this!

**Comment by ben-wes** [comment]
https://github.com/porres/pure-data/pull/45

**Comment by Lucarda** [comment]
@porres when all this is done and and ready for `Documentation` you can squash everything via

standing at `Documentation` branch

`git merge --squash manual-chapter2-revsion`

then you can commit. but i think it will be nice if we [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

you can add us in th commit message (leaving 2 blank lines)

```
blah blah.. 


Co-authored-by: Ben Wesch <benjamin.wesch@gmail.com>
Co-authored-by: Lucas Cordiviola <lucarda27@hotmail.com>
```

**Comment by porres** [comment]
what the hell is squash and why is it desired? :) I was just thinking about merging into docs and authorship of commits are preserved

**Comment by Lucarda** [comment]
Well `--squash` is to condense many commits in a single one. We can go without squashing if you like.

**Comment by Lucarda** [comment]
here https://github.com/pure-data/pddp/issues/92#issuecomment-1993600389 you liked the idea some days ago.


(i have to leave for a couple of hours)

**Comment by porres** [comment]
ok, more big revisions were made by me up to 2.4, I have included remarks that end with "!!!" for  @ben-wes  to include some more pics. I think we need to include a screenshot of 'audio' preferences, what do you think?

**Comment by porres** [comment]
> what do you think?

guess we can refer to chapter 3, but some revision could be done over there too

**Comment by Lucarda** [comment]
> guess we can refer to chapter 3, but some revision could be done over there too

I prefer "refer to chapter 3" and revisions there.

**Comment by Lucarda** [comment]
> > In Pcs, this menu shows the Ctrl + Q entry to quit Pd, which prompts you to confirm the action (in macs, this is under the Pd Menu). To quit without confirmation, use Ctrl + Shift + Q. (INCLUDE PIC AGAIN FIRST HERE FOR FILE MENU?!!!).

i think this is well written but it will take 2 pics, one for mac an one for pc. i think i don't need pics if i had read this.

**Comment by porres** [comment]
> I prefer "refer to chapter 3" and revisions there.

done

**Comment by porres** [comment]
> i think this is well written but it will take 2 pics, one for mac an one for pc. i think i don't need pics if i had read this.

I didnt mean about control + Q, just because we mention the File Menu and it could be the exact same screenshot

**Comment by porres** [comment]
or maybe just include back there at the beginning, since we don't need it as much later

**Comment by porres** [comment]
> or maybe just include back there at the beginning, since we don't need it as much later

we do have a text for 'Note the handy shortcuts', but this was here before without the pic... I think it makes sense to put it first and maybe tell people to look back

**Comment by porres** [comment]
let me test it

**Comment by Lucarda** [comment]
is this the only pic missing then?

![fig-editmode](https://github.com/pure-data/pddp/assets/25239522/cbb486bc-0193-445e-86de-dfb904b2a797)

**Comment by porres** [comment]
did it in https://github.com/porres/pure-data/commit/d60b18e2e910b1bb13c7fa6cf5628a6302cbc0d2 I think it looks good

**Comment by porres** [comment]
> is this the only pic missing then?

yes!

**Comment by porres** [comment]
> you can put 2 times the single pic :)

didn't seem worth it

**Comment by Lucarda** [comment]
ok. I'll add the new pic. in 2 minutes

**Comment by porres** [comment]
I guess I can fix it

**Comment by Lucarda** [comment]
i had just force push but wait

**Comment by porres** [comment]
Ok, this is finally done. A couple more revisions just to polish some more and I can merge

**Comment by Lucarda** [comment]
Ok. are you going to squash? (to not pollute much of Pd's commit history?)

**Comment by porres** [comment]
Ok, one request, in the first screenshot of Edit Menu, can you highlight the Font entry?

**Comment by Lucarda** [comment]
> Ok, one request, in the first screenshot of Edit Menu, can you highlight the Font entry?

yes

**Comment by porres** [comment]
> Ok. are you going to squash? (to not pollute much of Pd's commit history?)

I guess I can do that, but didn't plan cause I dunno how to do it ahahhahahah and it's already quite "clean" as Miller had recently merged... so I don't know if it is needed, and we can see in more details what happened. when not sqaushed, huh? Do you think Miller would really mind?

**Comment by Lucarda** [comment]
> Ok, one request, in the first screenshot of Edit Menu, can you highlight the Font entry?

done via https://github.com/porres/pure-data/pull/47

**Comment by Lucarda** [comment]
> I guess I can do that, but didn't plan cause I dunno how to do it ahahhahahah and it's already quite "clean" as Miller had recently merged... so I don't know if it is needed, and we can see in more details what happened. when not sqaushed, huh? Do you think Miller would really mind?

Ok no squashing.

**Comment by porres** [comment]
I say it's done and then revise and find many more things to do :) now I added one more task that we can maybe just move to another issue and discuss, which is to  document you can click on errors on the terminal to show in the patch where it is coming from...

**Comment by porres** [comment]
Ok, I moved it to another issue and I'm now gonna close this and reboot, cause it's time to finish it already
